on: push
name: deploy
jobs:
  deploy:
    name: deploy
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: install dependencies
      run: sudo -H pip3 install -r requirements.txt
    - name: run type checking and tests
      run: deploy/ci.sh